[project]
name = "bayes-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arviz>=0.23.0",
    "graphviz>=0.21",
    "marimo>=0.18.4",
    "matplotlib-fontja>=1.1.0",
    "pymc>=5.27.0",
]
